server:
  port: 8080
  http2:
    enabled: true
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stripe?allowPublicKeyRetrieval=true&useSSL=false&useServerPrepStmts=false&rewriteBatchedStatements=true&serverTimezone=GMT-3
    username: root
    password: root
    initialization-mode: always

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

stripe:
  apiKey: pk_test
  secretKey: sk_test
